### ISSUE TITLE
1.5.0 Mac Bug when unhiding App

### ISSUE THREAD

**Issue by raxelbrof** [edrlab/thorium-reader#1255]
Hi,

Loving 1.5.0, great to see Fixed Layout EPUB working so nicely.

There's an issue on macOS (High Sierra 10.13.6) where if Thorium is hidden, upon switching to it, if throws up an app-modal dialogue:

> An error has occurred in readium-desktop:main:redux:sagas:win:library:appActivateChannel
> 
>         Error message:
>         Cannot read property 'isMinimized' of undefined
> 

and nothing can be done in it, until you've selected OK.

![Screen Shot 2020-11-12 at 01 48 26 am](https://user-images.githubusercontent.com/64583201/98832968-35671680-2489-11eb-9d2e-827ad4321cd2.png)

**Comment by panaC** [comment]
Hello, thank you to report this.

this is potentially fixed with afab8bb287b71cb43b849b19f2213fe679a6d7de

can you test with the nightly build : https://github.com/edrlab/thorium-reader/releases/tag/latest-osx

**Comment by raxelbrof** [comment]
Tried 1.6.0-alpha.1.323935906 and the issue is still there.

I may not have correctly correctly described the problem:

If I manually hide Thorium: Thorium -> Hide Thorium then switch back to the app, the problem doesn't occur. However, I have an application which auto-hides background apps after a set period of time (Hocus Focus). when Hocus Focus hides Thorium, and then you switch back to it, the app-modal error comes up.

**Comment by panaC** [comment]
i've installed [Hocus Focus](http://hocusfoc.us/) on my mac macOs Catalina.
And didn't see the issue.

It works well.

**Comment by danielweck** [comment]
Closing due to lack of feedback / inactivity. Feel free to reopen in case the problem occurs again :)
