### ISSUE TITLE
Interactive diagram bug

### ISSUE THREAD

**Issue by Yodo13** [edrlab/thorium-reader#1377]
Hello, many thanks for the new version of the Thorium reader.

I would like to report a bug in the Thorium reader 1.6.0 (AppImage) that is related to interactive diagrams. I used paginated display. Here is how I can reproduce it:

1. Download this (free) book sample: [https://gobooks.com/books/epubs/sg0129_ki_k87_sample.epub](https://gobooks.com/books/epubs/sg0129_ki_k87_sample.epub)
 
2. Go to Chapter 1 "Some tesujis for making Sabaki".

3. (If necessary, go to the next page to see Diagram 1.) Click on Diagram 1, which activates the controls.

4. Press the ">" control button, which plays a move in Diagram 1.
 
5. Go to the next page with Diagram 2.
 
6. Click on Diagram 2.

Observed behavior: The view jumps back to Diagram 1.

Expected behavior: We remain with Diagram 2 and the controls are activated.

You can now move back to the page with Diagram 2 and see that the controls are indeed activated, but the jump back to Diagram 1 is annoying.

If this behavior is under your control, would it be possible to fix this?

**Comment by danielweck** [comment]
Hello, thank you for the detailed bug report. I think I understand what the bug is, and it might be tricky to fix. But I will take a look. Daniel

**Comment by danielweck** [comment]
I am not able to reproduce the bug anymore. I believe this was fixed in a recent update related to focus handling.

**Comment by Yodo13** [comment]
Thank you for looking into this.

I verified that the bug as described above is still present in Thorium-2.1.0.AppImage as used on Linux Mint 21. I did not try the most recent test build, as it seems only to fix some language issue.

Unless there is something that I can do, would it be possible to reopen this issue?
