### ISSUE TITLE
Feature: double-click to open an EPUB on Windows?

### ISSUE THREAD

**Issue by seaspeak** [edrlab/thorium-reader#1860]
I installed Thorium from Windows Store. (Windows 10)

If I double click an epub in Windows Explorer, Windows will bring up Thorium but not opening it.

Is that possible to let Thorium open the epub if it is already imported or import the epub and then open it? I think it is more intuitive.

**Comment by danielweck** [comment]
I believe this was fixed recently, will be soon published in Thorium version 2.2
In the meantime, could you please try a test build of Thorium from this link:
https://github.com/edrlab/thorium-reader/releases/tag/latest-windows
(please uninstall the Windows Store version and install the test version so that the EPUB file association works)

**Comment by danielweck** [comment]
I am closing the issue now as I think this was fixed, but I will re-open if the bug is confirmed.

**Comment by seaspeak** [comment]
How come this feature didn't come into version 2.2, Store and Thorium.Setup.2.2.0.exe?

**Comment by Donatzsky** [comment]
I can confirm that this issue persists, at least on Linux.

Running `thorium "path-to-epub"` simply opens the main window.

**Comment by danielweck** [comment]
AUR (Arch User Repository) is not officially supported by Thorium, but we definitely need to check that `thorium PATH_TO_EPUB` works in Windows, Linux and Mac:
* https://github.com/edrlab/thorium-reader/blob/004b6f06c67fc05db18e0f7c36081e63d8b59985/src/main/cli/index.ts#L100
* https://github.com/edrlab/thorium-reader/blob/004b6f06c67fc05db18e0f7c36081e63d8b59985/src/main/cli/command.ts#L148
There is also `thorium import PATH_TO_EPUB`:
* https://github.com/edrlab/thorium-reader/blob/004b6f06c67fc05db18e0f7c36081e63d8b59985/src/main/cli/index.ts#L60
* https://github.com/edrlab/thorium-reader/blob/004b6f06c67fc05db18e0f7c36081e63d8b59985/src/main/cli/command.ts#L68

**Comment by IllWriteDocumentationLater** [comment]
I too have this issue on Windows 10 using v2.2.0 from Github.

The issue is fixed when using v2.3-alpha.1.4415252165

**Comment by danielweck** [comment]
I have just tested the latest v2.3.0 official release in Windows and Linux, all works fine. Closing.

**Comment by seaspeak** [comment]
Issue persists on release v2.3.0 installed from the Windows Store.

**Comment by seaspeak** [comment]
> I have just tested the latest v2.3.0 official release in Windows and Linux, all works fine. Closing.

Issue persists on release v2.3.0 installed from the Windows Store.

**Comment by danielweck** [comment]
> Issue persists on release v2.3.0 installed from the Windows Store.

Hello, I have just tested Thorium v2.3.0 installed from the Window Store on a Windows 11 laptop that didn't have Thorium already installed (neither from the Microsoft Store nor from the executable installer downloaded from GitHub).
The "open with" and "double click" actions from the Windows File Explorer work fine, both when Thorium is completely closed or when the application is already open. When the EPUB is already imported in the bookshelf, Thorium avoids importing a duplicate and opens the reader window with the existing bookshelf EPUB.

**Comment by seaspeak** [comment]
Now I notice that both Thorium.Setup.2.3.0.exe version and Windows Store version has the issue. It happens randomly. Once it happens, I should restart Windows to get it back to work. I don't notice this issue with Thorium.Setup.2.3.0-alpha.1.3658607447.exe. I have Windows 10 professional.

# To reproduce
1. Install Thorium.Setup.2.3.0.exe or from Windows Store.
2. Open a new EPUB.  If "open with"/ "double click" doesn't work, then restart Windows.
3. Close the main Thorium window. (This step seems the key, most of time, after closing the main Thorium window, double-click-to-open won't work anymore.)
4. If it still works, may try deleting the book and try again.

**Comment by seaspeak** [comment]
Thorium 3.0 Store or DirectInstall sill has this problem. I am still using Thorium.Setup.2.3.0.exe.

**Comment by PaulCoddington** [comment]
> I am closing the issue now as I think this was fixed, but I will re-open if the bug is confirmed.

Still unable to open books by double-clicking in Explorer with Thorium 3.3.0 on Windows 11 25H2 26200.7628.

Thorium library launches, but the book is not opened.

**Comment by danielweck** [comment]
Thank you for reporting this. Please see https://github.com/edrlab/thorium-reader/discussions/3370

**Comment by PaulCoddington** [comment]
> Thank you for reporting this. Please see [#3370](https://github.com/edrlab/thorium-reader/discussions/3370)

Thanks for this link.

I have now uninstalled Thorium (EXE version), deleted registry keys (where possible), rebooted and reinstalled (EXE version). Problem persists.

**History of attempted resolutions:**

- Installed Store version to trial (Thorium never previously installed).
- Uninstalled Store version, installed EXE to attempt to resolve file association problem.
- Uninstalled EXE, deleted registry keys, reinstalled EXE.
- Also uninstalled another application that can open EPUB files (FrenchFry Cover), "just in case".

Of note, the reason why I am hoping to use Thorium as a viewer and open ebooks by double-clicking in Explorer is to avoid duplicate storage when adding them to the Library. Thorium copies books to the ``%AppData%`` folder and does not seem to have an option to link to them instead.
