### ISSUE TITLE
Reader state not properly storing on windows shutdown/log off/restart

### ISSUE THREAD

**Issue by nandakishore2009** [edrlab/thorium-reader#1986]
If you load a new Epub and make some changes like adding bookmark and do a window logoff, all the saved new book changes would be gone. Also on openings the Thorium again, we will see a book deleted warning toast.

PS: This issue become quite annoying for me when I read a lot of content and accidently shutdown it with out closing the reader, all my latest reading positional changes would be gone.

**Comment by panaC** [comment]
Hello, It's true, the application state is saved when closed. We maintain an internal modification patch and save it on shutdown so as not to overload the filesystem. We need to think about it, thanks to raising the issue.

**Comment by danielweck** [comment]
@panaC this is fixed now?

**Comment by panaC** [comment]
no, not actually fixed 

https://github.com/edrlab/thorium-reader/blob/518e0c19a5df298a3bece50d597bc2d3650a4c32/src/main/redux/sagas/persist.ts#L57

https://github.com/edrlab/thorium-reader/blob/518e0c19a5df298a3bece50d597bc2d3650a4c32/src/main/redux/sagas/persist.ts#L19

**Comment by danielweck** [comment]
Thank you, I thought so too. The reader state is now "instantly" saved without needing to close the reader window(s) but the persistence (storage I/O) is handled separately.
