### ISSUE TITLE
Double-clicking to open EPUB only works randomly on Windows

### ISSUE THREAD

**Issue by seaspeak** [edrlab/thorium-reader#2693]
It's not a bug. It works fine in a virtual environment, so I'm wondering if anyone has any ideas. I used to install Thorium.Setup.2.3.0-alpha.1.3658607447.exe, and that version was stable for this. Later versions only worked once or twice in rare cases.
It still brings up the main window, so it doesn't seem like a registry issue, and I've cleaned it up many times.
After the main window appears, how does Thorium pass the file path of the EPUB file, and then decide to import and open it?

Note:
Its success is limited to a few specific scenarios, such as immediately post-installation from the Microsoft Store or after a Windows reboot. Nonetheless, it quickly becomes unable to open a EPUB by double-clicking after the Thorium main window is closed, or even without closure. Even restarting Windows doesn't guarantee success.

**Comment by danielweck** [comment]
thank you for your tests and reports.
the randomness of the behaviour is weird.

note that the tip of the develop branch - and therefore the alpha test builds which are automatically created and uploaded to GitHub releases - contains changes (fixes) related to opening Thorium from double-clicking files (or "open with" menu) in the operating system file browser/explorer, also from registered URL schemes, and from the command line (which is a lesser-known feature).

 Thorium is an app that guarantees a single instance, so any request to open while already running triggers a different code path in the program execution, which is a little bit tricky to get right across Windows Linux and Mac (MacOS is also slightly different because conventionally the menu bar can remain active while there are no windows open, while in Linux and Windows world when no windows are open this usually means that there is no menu bar and the application is closed entirely.

**Comment by seaspeak** [comment]
When do you release v3.1.0? from #2494, this issue seemed to recur and was fixed again in v3.1.0.

**Comment by panaC** [comment]
We will release 3.1.0 as soon as possible in January 2025. I'm closing the issue for the moment.

**Comment by Marc2p** [comment]
I installed version 3.1.0 through the Microsoft Store and the problem remains. Only once I was able to open an epub file from the file explorer.
I'm using Windows 11 23H2 (AMD64) build 22631.4974

**Comment by danielweck** [comment]
PS: note that test builds differ from production releases in the following major ways:
* test builds do not support LCP-protected publications
* test builds store their settings and publication bookshelf in different folders (this means that users can install a production versions of Thorium from the Windows Store, and at the same time install a test version ... the books and settings will not be shared)

**Comment by Marc2p** [comment]
Both this and #2847  issues seem to be fixed with the test build.
Thank you
