### ISSUE TITLE
Scrolling causes text to jump back to a previous paragraph

### ISSUE THREAD

**Issue by Random-Nameless** [edrlab/thorium-reader#2936]
When scrolling using either the keyboard or the scrollwheel, the text suddenly jerks back to an earlier paragraph(usually the paragraph I start the scrolling from or the one after it). This occurs especially often when I suddenly scroll ahead by 3/4 of a page or more.  !I use the scrollable layout.

**Comment by danielweck** [comment]
Hello, I assume this is with Thorium 3.1.0? I believe this problem is already fixed and can be verified with the latest test builds available here in GitHub. Would you mind checking at your end? Thank you!

**Comment by Random-Nameless** [comment]
It appears I do indeed have thorium 3.1.0 , How does one  update the reader?

**Comment by danielweck** [comment]
you can download an installer for your operating system / architecture here from the releases section.

**Comment by Random-Nameless** [comment]
Which version should be downloaded for windows as the latest release besides the beta releases appears to be 3.1.0 which I already have.

**Comment by RonnyG2121** [comment]
I have the same problem, using any layout, paginated or scrollable. I also use screen readers.

**Comment by danielweck** [comment]
Hello, this problem has been fixed since Thorium version 3.1.0 could you please try the latest beta / test version and report back to confirm? Thank you very much! Regards, Daniel

**Comment by Random-Nameless** [comment]
@danielweck The issue persists even with the latest alpha version.

**Comment by RonnyG2121** [comment]
This problem has reappeared in this version.

**Comment by danielweck** [comment]
Thank you for confirming, we are aware of the regression bug (the cause is actually in Electron itself, there is no code change in Thorium). See https://github.com/edrlab/thorium-reader/issues/3106

**Comment by RonnyG2121** [comment]
In the last stable version, V3.3.0 this problem has reappeared

**Comment by danielweck** [comment]
this is strange. have you activated the screen reader support in the application preferences?

**Comment by RonnyG2121** [comment]
@danielweck I'm sorry, I didn't know this.
Now it's activate

**Comment by danielweck** [comment]
so just to be clear, you are using a screen reader?
